<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Проекты");
?><?$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"megamart", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "SITE_URL",
			1 => "CUSTOMER",
			2 => "SITE_DOMAIN",
			3 => "PHONE",
			4 => "GALLERY",
			5 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "28",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "SITE_URL",
			1 => "CUSTOMER",
			2 => "SITE_DOMAIN",
			3 => "PHONE",
			4 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "bootstrap",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "Y",
		"COMPONENT_TEMPLATE" => "megamart",
		"SEF_FOLDER" => "/projects/",
		"RS_LAZY_IMAGES_USE" => "FROM_MODULE",
		"IBLOCK_VIEW_MODE" => "VIEW_SECTIONS",
		"SECTIONS_TEMPLATE" => "projects",
		"DETAIL_TEMPLATE" => "main",
		"LIST_TEMPLATE" => "projects",
		"SECTIONS_SHOW_DESCRIPTION" => "Y",
		"LIST_SHOW_DESCRIPTION" => "Y",
		"SECTIONS_STAFF_TEMPLATE" => "from_widget",
		"SECTIONS_ASK_LINK" => "/include/forms/ask_staff/?element_id=#ELEMENT_ID#",
		"LIST_STAFF_TEMPLATE" => "from_widget",
		"LIST_ASK_LINK" => "/include/forms/ask_staff/?element_id=#ELEMENT_ID#",
		"SOCIAL_SERVICES" => array(
			0 => "facebook",
			1 => "moimir",
			2 => "odnoklassniki",
			3 => "twitter",
			4 => "vkontakte",
			5 => "",
		),
		"SOCIAL_COUNTER" => "N",
		"SOCIAL_COPY" => "first",
		"SOCIAL_LIMIT" => "",
		"SOCIAL_SIZE" => "m",
		"RS_FILE_PROP_GALLERY_VIEW" => "photogallery",
		"RSP_LIST_RS_TEMPLATE" => "from_widget",
		"RSP_LIST_SHOW_DESCRIPTION" => "Y",
		"RSP_LIST_ASK_LINK" => "/include/forms/ask_staff/?element_id=#ELEMENT_ID#",
		"RSP_LIST_RS_LIST_SECTION" => "l_section",
		"RSP_DETAIL_RS_FILE_PROP_GALLERY_VIEW" => "photogallery",
		"RSP_LIST_GRID_RESPONSIVE_SETTINGS" => "{\"xxs\":{\"items\":\"1\"},\"xs\":{\"items\":\"2\"},\"sm\":{\"items\":\"2\"},\"md\":{\"items\":\"3\"},\"lg\":{\"items\":\"3\"},\"xl\":{\"items\":\"3\"}}",
		"RSP_LIST_RS_LIST_SECTION_ADD_CONTAINER" => "N",
		"RSP_LIST_RS_LIST_SECTION_SHOW_TITLE" => "N",
		"RSP_LIST_RS_LIST_SECTION_SHOW_BUTTON" => "N",
		"RSP_LIST_RS_LIST_SECTION_BUTTON_NAME" => "",
		"RSP_LIST_RS_LIST_SECTION_BUTTON_LINK" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "",
			"section" => "#SECTION_CODE#/",
			"detail" => "#SECTION_CODE#/#ELEMENT_CODE#/",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>