<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("hide_section", "Y");
$APPLICATION->SetTitle("Отзывы");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"reviews", 
	array(
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"ADD_CONTAINER" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "reviews",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "",
		"GRID_RESPONSIVE_SETTINGS" => "{\"xxs\":{\"items\":\"1\"},\"xs\":{\"items\":\"2\"},\"sm\":{\"items\":\"2\"},\"lg\":{\"items\":\"4\"}}",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "35",
		"IBLOCK_TYPE" => "content",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"LINK_PROP" => "LINK",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "20",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "bootstrap",
		"PAGER_TITLE" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(
			0 => "AUTHOR_POSITION",
			1 => "AUTHOR_NAME",
			2 => "REVIEW",
			3 => "AUTHOR_PHOTO",
			4 => "",
		),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "SORT",
		"SORT_BY2" => "ID",
		"SORT_ORDER1" => "ASC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"TARGET_PROP" => "TARGET",
		"USE_OWL" => "N",
		"SLIDER_RESPONSIVE_SETTINGS" => "{\"0\":{\"items\":\"1\"}}",
		"OWL_CHANGE_SPEED" => "2000",
		"OWL_CHANGE_DELAY" => "8000",
		"SHOW_PARENT_TITLE" => "N",
		"PARENT_TITLE" => "Отзывы наших покупателей",
		"BLOCK_NAME_IS_LINK" => "N",
		"DISPLAY_DATE" => "Y",
		"PROP_AUTHOR_PHOTO" => "AUTHOR_PHOTO",
		"PROP_AUTHOR_NAME" => "AUTHOR_NAME",
		"PROP_AUTHOR_POSITION" => "AUTHOR_POSITION",
		"PROP_REVIEW" => "REVIEW",
		"ADD_SECTION" => "N",
		"SHOW_IBLOCK_DESCRIPTION" => "Y",
		"RS_LIST_SECTION" => "l_section",
		"RS_LIST_SECTION_SHOW_TITLE" => "N",
		"RS_LIST_SECTION_TITLE" => "Отзывы",
		"RS_LIST_SECTION_SHOW_BUTTON" => "N",
		"RS_LIST_SECTION_BUTTON_NAME" => "Посмотреть все",
		"RS_LIST_SECTION_BUTTON_LINK" => "/company/reviews"
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>