<?$APPLICATION->IncludeComponent(
	"bitrix:news.line",
	"newslist",
	array(
		"COMPONENT_TEMPLATE" => "newslist",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "300",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "NAME",
			3 => "SORT",
			4 => "PREVIEW_TEXT",
			5 => "PREVIEW_PICTURE",
			6 => "DATE_ACTIVE_FROM",
			7 => "ACTIVE_FROM",
			8 => "IBLOCK_TYPE_ID",
			9 => "IBLOCK_ID",
			10 => "IBLOCK_CODE",
			11 => "IBLOCK_NAME",
			12 => "DATE_CREATE",
			13 => "",
		),
		"IBLOCKS" => array(
			0 => "20",
			1 => "21",
			2 => "#ARTICLES_ARTICLES_IBLOCK_ID#",
		),
		"IBLOCK_TYPE" => "articles",
		"NEWS_COUNT" => "4",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"RS_TAG_20_COLOR" => "#54b704",
		"RS_TAG_21_COLOR" => "#009cff",
		"RS_TAG_#ARTICLES_ARTICLES_IBLOCK_ID#_COLOR" => "#ff0000",
		"RS_SUMMARY_PAGE" => "",
		"ADD_CONTAINER" => "Y",
		"ADD_SECTION" => "Y",
		"SHOW_PARENT_TITLE" => "Y",
		"PARENT_TITLE" => "Полезная информация",
		"BLOCK_NAME_IS_LINK" => "N",
		"GRID_RESPONSIVE_SETTINGS" => "{\"xxs\":{\"items\":\"1\"},\"xs\":{\"items\":\"2\"},\"sm\":{\"items\":\"2\"},\"md\":{\"items\":\"3\"},\"lg\":{\"items\":\"4\"},\"xl\":{\"items\":\"4\"}}",
		"RS_USE_SUMMARY_PAGE" => "Y",
		"RS_SUMMARY_PAGE_TITLE" => "Посмотреть все",
		"RS_SUMMARY_PAGE_LINK" => "/info/",
		"RS_SHOW_IBLOCK" => "Y",
		"RS_LIST_SECTION" => "l_section",
		"RS_LIST_SECTION_ADD_CONTAINER" => "Y",
		"RS_LIST_SECTION_SHOW_TITLE" => "Y",
		"RS_LIST_SECTION_TITLE" => "Полезная информация",
		"RS_LIST_SECTION_SHOW_BUTTON" => "Y",
		"RS_LIST_SECTION_BUTTON_NAME" => "Посмотреть все",
		"RS_LIST_SECTION_BUTTON_LINK" => "/info/"
	),
	false
);?>