<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list", 
	"catalog", 
	array(
		"COMPONENT_TEMPLATE" => "catalog",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "17",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"COUNT_ELEMENTS" => "N",
		"TOP_DEPTH" => "2",
		"SECTION_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"VIEW_MODE" => "TILE",
		"SHOW_PARENT_TITLE" => "Y",
		"HIDE_SECTION_NAME" => "N",
		"SECTION_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SET_TITLE" => "N",
		"ADD_CONTAINER" => "Y",
		"SECTIONS_VIEW_MODE" => "TILE",
		"GRID_RESPONSIVE_SETTINGS" => "{\"xxs\":{\"items\":\"1\"},\"sm\":{\"items\":\"2\"},\"lg\":{\"items\":\"4\"}}",
		"PARENT_TITLE" => "Каталог товаров",
		"PARENT_URL" => "/catalog/",
		"RS_LAZY_IMAGES_USE" => "Y",
		"SHOW_PARENT_NAME" => "Y",
		"RS_LIST_SECTION" => "l_section",
		"RS_LIST_SECTION_ADD_CONTAINER" => "Y",
		"RS_LIST_SECTION_SHOW_TITLE" => "Y",
		"RS_LIST_SECTION_TITLE" => "Каталог товаров",
		"RS_LIST_SECTION_SHOW_BUTTON" => "Y",
		"RS_LIST_SECTION_BUTTON_NAME" => "Посмотреть все",
		"RS_LIST_SECTION_BUTTON_LINK" => "/catalog/",
		"LVL1_SECTION_COUNT" => "12",
		"COUNT_ELEMENTS_FILTER" => "CNT_ACTIVE",
		"FILTER_NAME" => "sectionsFilter",
		"CACHE_FILTER" => "N"
	),
	false
);?>